import { type NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
	const { status } = useSession();

	const cardStyles = "flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20";

	return (
		<>
			<Head>
				<title>Activity Logger</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
				<div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
					<h1 className="flex flex-col font-extrabold tracking-tight text-white sm:text-[5rem] text-center">
						<span className="text-9xl underline underline-offset-1 text-[hsl(280,100%,70%)]">Gogotzumon</span>
						<span className="text-6xl">The Activity Logger</span>
					</h1>
					<div className="flex flex-row gap-2">
						<Link
							className={cardStyles}
							href="https://create.t3.gg/en/introduction"
							target="_blank"
						>
							<h2 className="text-3xl font-bold">App built on create-t3-app</h2>
							<h3 className="text-2xl font-bold">Documentation →</h3>
							<div className="text-lg">
								Learn more about Create T3 App, the libraries it uses, and how
								to deploy it.
							</div>
						</Link>
						<div className={cardStyles}>
							<h2 className="text-3xl font-bold">What even is this?</h2>
							<h3 className="text-2xl font-bold">Log Daily, Daily Log</h3>
							<div className="text-lg">
								This is meant as a simple web application to log some activites
								done through the day, week, month and year
							</div>
						</div>
						<div className={cardStyles}>
							<h2 className="text-3xl font-bold">Auth Showcase</h2>
							<h3 className="text-2xl font-bold">{status}</h3>
							<AuthShowcase />
						</div>
					</div>
				</div>
			</main>
		</>
	);
};

export default Home;

const AuthShowcase: React.FC = () => {
	const { data: sessionData } = useSession();

	const { data: secretMessage } = trpc.auth.getSecretMessage.useQuery(
		undefined, // no input
		{ enabled: sessionData?.user !== undefined },
	);

	console.log(sessionData, secretMessage);

	return (
		<div className="flex flex-col items-center justify-center gap-4">
			<p className="text-center text-2xl text-white">
				{sessionData && <span>Logged in as {sessionData?.user?.name}</span>}
				{secretMessage && <span> - {secretMessage}</span>}
			</p>
			<button
				className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
				onClick={sessionData ? () => signOut() : () => signIn()}
			>
				{sessionData ? "Sign out" : "Sign in"}
			</button>
		</div>
	);
};
